#!/usr/bin/env python3
"""Create THC Analytics dashboards in Metabase v0.61.x.
Requirements:
    pip install requests python-dotenv
Usage:
    1) Copy .env.example to .env and fill credentials.
    2) List databases:
       python scripts\\create_metabase_dashboard.py --list-databases
    3) Set METABASE_DATABASE_ID in .env.
    4) Create/update dashboards:
       python scripts\\create_metabase_dashboard.py
Notes:
    Metabase v0.61 does not support the old POST /api/dashboard/:id/cards endpoint.
    This script updates dashboard cards through PUT /api/dashboard/:id.
"""
from __future__ import annotations
import argparse
import os
import sys
from dataclasses import dataclass
from typing import Any
import requests
try:
    from dotenv import load_dotenv
except Exception:
    load_dotenv = None
METABASE_URL = os.environ.get("METABASE_URL", "http://localhost:3000")
COLLECTION_NAME = "THC Analytics"
TIMEOUT = 60
@dataclass
class Question:
    name: str
    sql: str
    display: str
    visualization_settings: dict[str, Any]
@dataclass
class DashboardCard:
    question_name: str
    x: int
    y: int
    w: int
    h: int
@dataclass
class DashboardSpec:
    name: str
    description: str
    cards: list[DashboardCard]
def getenv_required(name: str) -> str:
    value = os.environ.get(name)
    if not value:
        raise SystemExit(f"Missing required environment variable: {name}")
    return value
def request(session: requests.Session, method: str, path: str, **kwargs: Any) -> Any:
    url = f"{METABASE_URL.rstrip('/')}{path}"
    response = session.request(method, url, timeout=TIMEOUT, **kwargs)
    if response.status_code >= 400:
        print(f"\nHTTP {response.status_code} {method} {url}", file=sys.stderr)
        try:
            print(response.json(), file=sys.stderr)
        except Exception:
            print(response.text, file=sys.stderr)
        response.raise_for_status()
    if response.text:
        try:
            return response.json()
        except Exception:
            return response.text
    return None
def login() -> requests.Session:
    if load_dotenv:
        load_dotenv()
    email = getenv_required("METABASE_EMAIL")
    password = getenv_required("METABASE_PASSWORD")
    session = requests.Session()
    payload = {"username": email, "password": password}
    data = request(session, "POST", "/api/session", json=payload)
    token = data["id"]
    session.headers.update({"X-Metabase-Session": token})
    return session
def list_databases(session: requests.Session) -> None:
    data = request(session, "GET", "/api/database")
    for db in data.get("data", []):
        print(f'{db["id"]}: {db["name"]} ({db.get("engine")})')
def get_database_id() -> int:
    value = getenv_required("METABASE_DATABASE_ID")
    try:
        return int(value)
    except ValueError as exc:
        raise SystemExit("METABASE_DATABASE_ID must be an integer") from exc
def get_or_create_collection(session: requests.Session) -> int:
    collections = request(session, "GET", "/api/collection")
    for item in collections:
        if item.get("name") == COLLECTION_NAME:
            return int(item["id"])
    created = request(session, "POST", "/api/collection", json={"name": COLLECTION_NAME, "description": "theHunter Classic analytics dashboards"})
    return int(created["id"])
def native_query(database_id: int, sql: str) -> dict[str, Any]:
    return {
        "database": database_id,
        "type": "native",
        "native": {"query": sql, "template-tags": {}},
    }
def list_cards_in_collection(session: requests.Session, collection_id: int) -> list[dict[str, Any]]:
    try:
        cards = request(session, "GET", f"/api/card?f=all&collection={collection_id}")
        if isinstance(cards, list):
            return cards
    except requests.HTTPError:
        pass
    search = request(session, "GET", "/api/search", params={"models": "card", "collection": collection_id})
    return [item for item in search.get("data", []) if item.get("model") == "card"]
def make_question(session: requests.Session, collection_id: int, database_id: int, q: Question) -> int:
    existing = list_cards_in_collection(session, collection_id)
    for card in existing:
        if card.get("name") == q.name:
            card_id = int(card["id"])
            payload = {
                "name": q.name,
                "description": "Generated by THC dashboard automation",
                "dataset_query": native_query(database_id, q.sql),
                "display": q.display,
                "visualization_settings": q.visualization_settings,
                "collection_id": collection_id,
            }
            try:
                request(session, "PUT", f"/api/card/{card_id}", json=payload)
                print(f"Question updated: {q.name} -> {card_id}")
            except requests.HTTPError:
                print(f"Question exists: {q.name} -> {card_id}")
            return card_id
    payload = {
        "name": q.name,
        "description": "Generated by THC dashboard automation",
        "dataset_query": native_query(database_id, q.sql),
        "display": q.display,
        "visualization_settings": q.visualization_settings,
        "collection_id": collection_id,
        "result_metadata": None,
    }
    created = request(session, "POST", "/api/card", json=payload)
    print(f"Question created: {q.name} -> {created['id']}")
    return int(created["id"])
def get_or_create_dashboard(session: requests.Session, collection_id: int, spec: DashboardSpec) -> int:
    search = request(session, "GET", "/api/search", params={"q": spec.name})
    for item in search.get("data", []):
        if item.get("model") == "dashboard" and item.get("name") == spec.name:
            dashboard_id = int(item["id"])
            request(session, "PUT", f"/api/dashboard/{dashboard_id}", json={"name": spec.name, "description": spec.description, "collection_id": collection_id})
            print(f"Dashboard exists: {spec.name} -> {dashboard_id}")
            return dashboard_id
    payload = {"name": spec.name, "description": spec.description, "collection_id": collection_id}
    created = request(session, "POST", "/api/dashboard", json=payload)
    print(f"Dashboard created: {spec.name} -> {created['id']}")
    return int(created["id"])
def make_dashcard(dashboard_id: int, card_id: int, x: int, y: int, w: int, h: int, temp_id: int) -> dict[str, Any]:
    return {
        "id": temp_id,
        "dashboard_id": dashboard_id,
        "card_id": card_id,
        "card": {"id": card_id},
        "row": y,
        "col": x,
        "size_x": w,
        "size_y": h,
        "parameter_mappings": [],
        "visualization_settings": {},
        "series": [],
    }
def update_dashboard_layout(session: requests.Session, dashboard_id: int, cards: list[DashboardCard], card_ids: dict[str, int]) -> None:
    dashcards = [
        make_dashcard(dashboard_id, card_ids[item.question_name], item.x, item.y, item.w, item.h, -index - 1)
        for index, item in enumerate(cards)
    ]
    payload_variants = [
        {"dashcards": dashcards},
        {"cards": dashcards},
        {"ordered_cards": dashcards},
    ]
    last_error: Exception | None = None
    for payload in payload_variants:
        try:
            request(session, "PUT", f"/api/dashboard/{dashboard_id}", json=payload)
            return
        except requests.HTTPError as exc:
            last_error = exc
    raise RuntimeError(f"Could not update dashboard {dashboard_id} layout") from last_error
def settings_table(cols: list[str] | None = None) -> dict[str, Any]:
    return {"table.columns": cols or []}
def settings_bar(x: str, y: str, color: str = "#7fb069") -> dict[str, Any]:
    return {"graph.dimensions": [x], "graph.metrics": [y], "graph.colors": [color]}
def settings_line(x: str, ys: list[str]) -> dict[str, Any]:
    return {"graph.dimensions": [x], "graph.metrics": ys, "graph.colors": ["#d97706", "#3b82f6", "#7fb069"]}
QUESTIONS = [
    Question("01 - Hunter - KPI Overview","SELECT handle, hostname, hunter_score, rank_no, lifetime_hours, lifetime_km, lifetime_kills, lifetime_ethical_kills, ROUND(lifetime_ethical_kills::numeric / NULLIF(lifetime_kills, 0) * 100, 2) AS ethical_pct FROM api.vw_hunter_overview;","table",settings_table()),
    Question("02 - Hunter - Weekly Activity","SELECT week_start, expeditions, kills, collectables, hours, kills_per_hour FROM api.vw_expedition_weekly ORDER BY week_start;","line",settings_line("week_start",["kills","hours","expeditions"])),
    Question("03 - Hunter - Reserve Performance","SELECT reserve_name, expeditions, kills, collectables, hours, kills_per_expedition, kills_per_hour FROM api.vw_reserve_performance ORDER BY kills DESC;","bar",settings_bar("reserve_name","kills","#7fb069")),
    Question("04 - Weapons - Top Kills","SELECT weapon_name, kills, hits, misses, accuracy_pct, ethical_pct, lethality_pct, avg_distance_per_kill FROM api.vw_weapon_analytics WHERE kills > 0 ORDER BY kills DESC;","bar",settings_bar("weapon_name","kills","#d97706")),
    Question("05 - Weapons - Accuracy","SELECT weapon_name, accuracy_pct, hits, misses FROM api.vw_weapon_analytics WHERE hits > 0 ORDER BY accuracy_pct DESC NULLS LAST;","bar",settings_bar("weapon_name","accuracy_pct","#3b82f6")),
    Question("06 - Weapons - Ethical Rate","SELECT weapon_name, ethical_pct, kills, ethical_kills FROM api.vw_weapon_analytics WHERE kills > 0 ORDER BY ethical_pct DESC NULLS LAST;","bar",settings_bar("weapon_name","ethical_pct","#7fb069")),
    Question("07 - Weapons - Efficiency Scatter","SELECT weapon_name, hits, kills, misses, accuracy_pct, ethical_pct, avg_distance_per_kill FROM api.vw_weapon_analytics WHERE hits > 0 ORDER BY hits DESC;","scatter",{"graph.dimensions":["hits"],"graph.metrics":["kills"],"graph.colors":["#d97706"]}),
    Question("08 - Species - Distribution","SELECT species_name, kills, ethical_kills, spots, tracks, ethical_pct, kill_share_pct FROM api.vw_species_analytics WHERE kills > 0 ORDER BY kills DESC;","pie",{"pie.dimension":"species_name","pie.metric":"kills","graph.colors":["#2f855a","#d6a84f","#d97706","#3b82f6","#d14b4b"]}),
    Question("09 - Species - Hardest","SELECT species_name, kills, tracks, spots, tracks_per_kill, spots_per_kill FROM api.vw_species_analytics WHERE kills > 0 ORDER BY tracks_per_kill DESC NULLS LAST;","bar",settings_bar("species_name","tracks_per_kill","#d6a84f")),
    Question("10 - Species - Ethical Rate","SELECT species_name, kills, ethical_kills, ethical_pct FROM api.vw_species_analytics WHERE kills >= 5 ORDER BY ethical_pct DESC NULLS LAST;","bar",settings_bar("species_name","ethical_pct","#7fb069")),
    Question("11 - Hall of Fame - Score Records","SELECT species_name, animal_id, score, distance, weapon_name, confirm_at, gender, texture FROM api.vw_personal_records WHERE record_type = 'score' ORDER BY score DESC NULLS LAST;","table",settings_table()),
    Question("12 - Hall of Fame - Distance Records","SELECT species_name, animal_id, distance, score, weapon_name, confirm_at, gender, texture FROM api.vw_personal_records WHERE record_type = 'distance' ORDER BY distance DESC NULLS LAST;","table",settings_table()),
    Question("13 - Leaderboards - Load Control","SELECT leaderboard_type, COUNT(DISTINCT species_name) AS species_count, COUNT(*) AS rows_count FROM api.vw_leaderboard_top100 GROUP BY leaderboard_type ORDER BY leaderboard_type;","table",settings_table()),
    Question("14 - Leaderboards - Score Top 100","SELECT species_name, animal_id, rank_no, handle, score, score_type FROM api.vw_leaderboard_top100 WHERE leaderboard_type = 'score' ORDER BY species_name, rank_no;","table",settings_table()),
    Question("15 - Leaderboards - Range Top 100","SELECT species_name, animal_id, rank_no, handle, score, score_type FROM api.vw_leaderboard_top100 WHERE leaderboard_type = 'range' ORDER BY species_name, rank_no;","table",settings_table()),
    Question("16 - Leaderboards - Hunter Placement","SELECT l.leaderboard_type, l.species_name, l.rank_no, l.handle, l.score FROM api.vw_leaderboard_top100 l JOIN api.vw_hunter_overview h ON lower(l.handle) = lower(h.handle) ORDER BY l.leaderboard_type, l.rank_no;","table",settings_table()),
]
DASHBOARDS = [
    DashboardSpec("THC - Hunter Overview","Resumen general del cazador",[DashboardCard("01 - Hunter - KPI Overview",0,0,24,4),DashboardCard("02 - Hunter - Weekly Activity",0,4,16,8),DashboardCard("03 - Hunter - Reserve Performance",16,4,8,8)]),
    DashboardSpec("THC - Weapon Analytics","Análisis de armas",[DashboardCard("04 - Weapons - Top Kills",0,0,12,8),DashboardCard("05 - Weapons - Accuracy",12,0,12,8),DashboardCard("06 - Weapons - Ethical Rate",0,8,12,8),DashboardCard("07 - Weapons - Efficiency Scatter",12,8,12,8)]),
    DashboardSpec("THC - Species Analytics","Análisis de especies",[DashboardCard("08 - Species - Distribution",0,0,12,8),DashboardCard("09 - Species - Hardest",12,0,12,8),DashboardCard("10 - Species - Ethical Rate",0,8,24,8)]),
    DashboardSpec("THC - Hall of Fame","Records personales",[DashboardCard("11 - Hall of Fame - Score Records",0,0,12,10),DashboardCard("12 - Hall of Fame - Distance Records",12,0,12,10)]),
    DashboardSpec("THC - Leaderboards","Clasificaciones globales",[DashboardCard("13 - Leaderboards - Load Control",0,0,24,4),DashboardCard("14 - Leaderboards - Score Top 100",0,4,12,12),DashboardCard("15 - Leaderboards - Range Top 100",12,4,12,12),DashboardCard("16 - Leaderboards - Hunter Placement",0,16,24,6)]),
]
def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--list-databases", action="store_true")
    args = parser.parse_args()
    session = login()
    if args.list_databases:
        list_databases(session)
        return
    database_id = get_database_id()
    collection_id = get_or_create_collection(session)
    card_ids = {q.name: make_question(session, collection_id, database_id, q) for q in QUESTIONS}
    for spec in DASHBOARDS:
        dashboard_id = get_or_create_dashboard(session, collection_id, spec)
        update_dashboard_layout(session, dashboard_id, spec.cards, card_ids)
        print(f"Dashboard ready: {spec.name} -> {METABASE_URL.rstrip('/')}/dashboard/{dashboard_id}")
    print("Done.")
if __name__ == "__main__":
    main()
